require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/pizza_toppings", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # PizzaTopping. As you add validations to PizzaTopping, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PizzaTopping.create! valid_attributes
      get pizza_toppings_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      pizza_topping = PizzaTopping.create! valid_attributes
      get pizza_topping_url(pizza_topping)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_pizza_topping_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      pizza_topping = PizzaTopping.create! valid_attributes
      get edit_pizza_topping_url(pizza_topping)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PizzaTopping" do
        expect {
          post pizza_toppings_url, params: { pizza_topping: valid_attributes }
        }.to change(PizzaTopping, :count).by(1)
      end

      it "redirects to the created pizza_topping" do
        post pizza_toppings_url, params: { pizza_topping: valid_attributes }
        expect(response).to redirect_to(pizza_topping_url(PizzaTopping.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PizzaTopping" do
        expect {
          post pizza_toppings_url, params: { pizza_topping: invalid_attributes }
        }.to change(PizzaTopping, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post pizza_toppings_url, params: { pizza_topping: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested pizza_topping" do
        pizza_topping = PizzaTopping.create! valid_attributes
        patch pizza_topping_url(pizza_topping), params: { pizza_topping: new_attributes }
        pizza_topping.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the pizza_topping" do
        pizza_topping = PizzaTopping.create! valid_attributes
        patch pizza_topping_url(pizza_topping), params: { pizza_topping: new_attributes }
        pizza_topping.reload
        expect(response).to redirect_to(pizza_topping_url(pizza_topping))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        pizza_topping = PizzaTopping.create! valid_attributes
        patch pizza_topping_url(pizza_topping), params: { pizza_topping: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested pizza_topping" do
      pizza_topping = PizzaTopping.create! valid_attributes
      expect {
        delete pizza_topping_url(pizza_topping)
      }.to change(PizzaTopping, :count).by(-1)
    end

    it "redirects to the pizza_toppings list" do
      pizza_topping = PizzaTopping.create! valid_attributes
      delete pizza_topping_url(pizza_topping)
      expect(response).to redirect_to(pizza_toppings_url)
    end
  end
end
