default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: smassessment_development

test:
  <<: *default
  database: smassessment_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

cable:
  adapter: postgresql
  url: <%= ENV["DATABASE_URL"] %>